name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow pushing changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate the snake
        id: generate_snake
        uses: Platane/snk@master
        with:
          github_user_name: Ryuk0010
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Set output for debugging
        id: set_output
        run: |
          # Example: capture output for debugging purposes
          output_value=$(ls dist)  # Adjust to capture relevant output
          echo "OUTPUT_VALUE=${output_value}" >> $GITHUB_ENV

      - name: Show status
        run: git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
